### ISSUE TITLE
Installation Instruction?

### ISSUE THREAD

**Issue by Palpatineli** [ricklisz/AnatoMask#1]
Thanks for your very interesting and insightful paper. However your code repo looks somewhat strange: it doesn't seem to be a full fork of nnunet v2, not having pyproject.toml or setup.py. When I follow the first step in your instruction and run `pip install -e .`, as expected I got the error: `ERROR: file:///*/AnatoMask does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.`

Can you provide further instruction on how to proceed? Should I simply load my venv for nnunetv2 and run your code as scripts, or copy the files in your repo over the master branch of nnunetv2?

**Comment by ricklisz** [comment]
Hi, thanks for letting me know. I just fixed the repo by adding the setup.py and toml file. Let me know if it still doesn't work.
